### ISSUE TITLE
EditorApp.m display nothing but a face image.

### ISSUE THREAD

**Issue by leaf918** [icygurkirat/3DMM-Matlab#2]

**Comment by leaf918** [comment]
![image](https://user-images.githubusercontent.com/170311/34602241-03ff585c-f23a-11e7-9fee-5e19bd2d9396.png)

**Comment by icygurkirat** [comment]
The EditorApp.m is a GUI app created using some GUI interface in MATLAB. It actually has a series of sliders to change some parameters and simultaneously display its preview (on the face you see). 
Due to higher resolution of my screen (3840x2160), I had set the window size of that order. The sliders are there on your window as well, but due to lower resolution, you are unable to see them. If you wish to run on lower resolution screens, I would advise you to open "EditorApp.fig" in MATLAB. It contains the layout (along with window size, etc) of the GUI. You can resize the elements to fit your screen's resolution.
