### ISSUE TITLE
is this script work right??

### ISSUE THREAD

**Issue by leaf918** [icygurkirat/3DMM-Matlab#4]

**Comment by leaf918** [comment]
![image](https://user-images.githubusercontent.com/170311/34716182-0f9499ec-f56a-11e7-94d7-b3ba4bf86439.png)

**Comment by icygurkirat** [comment]
Seems correct. If you are able to change the face params and attributes, the script is working fine!! If you are still facing problems due to high resolution of gui structure, pull the rep again. Due to the latest commit, the GUI will scale well according to your display. If it still does not, resizing the window (using maximize button or from window boundary) will scale it properly.
